---
apiVersion: v1
kind: Namespace
metadata:
  name: renovate 
  labels:
    name: renovate 
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate 
  namespace: renovate
spec:
  schedule: "0 5 * * 6"
  timeZone: America/Chicago
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: renovate 
            image: renovate/renovate 
            imagePullPolicy: IfNotPresent
            command: 
            - renovate
            - --pr-hourly-limit 
            - "0"
            - wizardlyEinstein/immich
            - wizardlyEinstein/teslamate
            - wizardlyEinstein/cert-manager
            - wizardlyEinstein/vault
            - wizardlyEinstein/plex
            - wizardlyEinstein/home
            - wizardlyEinstein/bluesky
            - wizardlyEinstein/unifi
            - wizardlyEinstein/renovate
            - wizardlyEinstein/ollama
            - wizardlyEinstein/open-webui
            - wizardlyEinstein/argocd
            env:
            - name: LOG_LEVEL 
              value: debug 
            - name: RENOVATE_TOKEN 
              valueFrom:
                secretKeyRef:
                  name: renovate 
                  key: RENOVATE_TOKEN
          restartPolicy: Never 
